# -*- coding: utf-8 -*-
"""Predicting Student Dropout and Academic Success: A Responsible AI Approach.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpPV-3Ko1Oq0S0YTixOia53oAoVtl9XB
"""

!pip install lime fairlearn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import xgboost as xgb
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix, classification_report
import shap
from lime.lime_tabular import LimeTabularExplainer
from sklearn.metrics import recall_score, make_scorer
from fairlearn.metrics import  selection_rate
from fairlearn.reductions import ExponentiatedGradient, DemographicParity
from sklearn.linear_model import LogisticRegression
from fairlearn.metrics import MetricFrame, demographic_parity_difference, equalized_odds_difference

from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/datasets/Predict_Student_Dropout_and_Academic_Success.csv"
# Make sure to set the correct delimiter
df = pd.read_csv(file_path, delimiter=";")

print(df.shape)
df.head()

df.info()

"""⚠️ Important: Many columns look numeric but are actually categorical codes
(e.g., Marital status: 1=single, 2=married; Nationality: 1=Portuguese, 2=Angolan, etc.).
If we leave them as plain integers, the neural network will wrongly assume they have
a numeric order (e.g., 'Married(2)' > 'Single(1)'), which is meaningless.

✅ Solution for neural networks:
  1. First, explicitly mark these columns as categorical in pandas (so we keep track of them).
   2. Later, we will encode them for PyTorch:
      - One-hot encoding (for low-cardinality features, e.g., Marital status).
      - Embedding layers (for high-cardinality features, e.g., Course, Nationality).

This ensures the model treats categories as separate classes, not ordered numbers.

"""

# Columns that are categorical but stored as numbers
categorical_cols = [
    'Marital status', 'Application mode', 'Application order',
    'Course', 'Previous qualification', 'Nacionality',
    'Mother\'s qualification', 'Father\'s qualification',
    'Mother\'s occupation', 'Father\'s occupation'
]


# Convert to category dtype
for col in categorical_cols:
    df[col] = df[col].astype('category')

df[categorical_cols].head()

df.describe()

"""Dropping macroeconomic features (Unemployment rate, Inflation rate, GDP)
These variables reflect year-level economic conditions, not individual student characteristics.
They can leak admission year information and introduce bias, since the model could exploit differences between cohorts instead of focusing on student-level pre-enrollment features.
Therefore, we exclude them for a fairer and cleaner model.

"""

# Check unique values and counts
print(df['Target'].value_counts())

# Plot distribution
df['Target'].value_counts().plot(kind='bar', color='skyblue')
plt.title("Target Distribution (Graduate vs Dropout vs Enrolled)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

df = df.drop(columns=["Unemployment rate", "Inflation rate", "GDP"])

"""⚠️ Removing "leaky" features:
These columns contain information that would only be known *after* a student has already started or even finished their studies
(e.g., grades, credits, enrollment evaluations).
Keeping them would give the model unfair "hints" about the target (Graduate/Dropout),
leading to overly optimistic results (data leakage). For a fair prediction task, we only keep features available at the time of enrollment.
"""

leaky_features = [
    'Curricular units 1st sem (credited)',
    'Curricular units 1st sem (enrolled)',
    'Curricular units 1st sem (evaluations)',
    'Curricular units 1st sem (approved)',
    'Curricular units 1st sem (grade)',
    'Curricular units 1st sem (without evaluations)',
    'Curricular units 2nd sem (credited)',
    'Curricular units 2nd sem (enrolled)',
    'Curricular units 2nd sem (evaluations)',
    'Curricular units 2nd sem (approved)',
    'Curricular units 2nd sem (grade)',
    'Curricular units 2nd sem (without evaluations)',
]

df = df.drop(columns=leaky_features)

# Map text labels to numeric codes, overwrite Target column
target_mapping = {
    "Graduate": 0,
    "Dropout": 1,
    "Enrolled": 2
}

df['Target'] = df['Target'].map(target_mapping).astype(int)

# Confirm changes
print(df['Target'].value_counts())
print(df.dtypes['Target'])

df.info()

"""**EDA**

Distribution of Numerical Features
"""

# This helps us see skewness, ranges, and potential outliers.
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.drop('Target')

df[numeric_cols].hist(bins=30, figsize=(15,10))
plt.suptitle("Histograms of Numeric Features")
plt.show()

"""Correlation Between Numerical Features"""

# This helps detect multicollinearity (features that are strongly correlated).
plt.figure(figsize=(12,8))
sns.heatmap(df[numeric_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap of Numeric Features")
plt.show()

"""**Categorical Feature Cardinality**

Number of unique categories per categorical feature
This helps us spot high-cardinality columns (many unique values), which may need special handling.
"""

cat_cols = df.select_dtypes(include=['category']).columns

for col in cat_cols:
    print(f"{col}: {df[col].nunique()} unique values")

"""**Distribution of Categorical Features**

We want to see if some categories dominate (e.g., one nationality is 90% of data).
"""

for col in cat_cols:
    plt.figure(figsize=(10,4))
    df[col].value_counts().plot(kind='bar')
    plt.title(f"Distribution of {col}")
    plt.show()

"""Target vs Categorical Features

Target distribution across categories helps us see patterns like: Do certain groups (e.g., Gender, Nationality) have more dropouts?
for col in cat_cols:
"""

cat_cols = df.select_dtypes(include=['category']).columns
for col in cat_cols:
    plt.figure(figsize=(10,4))
    sns.countplot(data=df, x=col, hue="Target")
    plt.title(f"Target Distribution by {col}")
    plt.xticks(rotation=45)
    plt.show()

"""

*   Marital status '2' (married) shows higher dropout rates.
*   Courses 9119, 9140, 9991 have more students dropping out.

*   Application mode 39 (students over 23 years old) shows higher dropout rates.
*   Mother's qualification and father's qualification '37' (Basic education 1st cycle) has a high dropout rate, close to graduates.

*   Mother's occupation (unskilled workers) and father's occupation reflect high counts in both graduates and dropouts.
"""

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
num_cols = [col for col in num_cols if col != 'Target']  # exclude target

for col in num_cols:
    plt.figure(figsize=(10,4))
    # Histogram + KDE by target
    sns.histplot(data=df, x=col, hue="Target", kde=True, bins=30, palette="Set2", alpha=0.6)
    plt.title(f"Distribution of {col} by Target")
    plt.show()

"""**Observations**

Gender: Male students have a higher dropout rate compared to female students.

Financial status: Students who are  debtors or have unpaid tuition fees show higher dropout rates.

Age: Students aged 25+ are more likely to drop out than younger students.

**PREPROCESSING**

**Note on Sensitive Attributes and Fairness**

In fairness-aware machine learning, features such as Gender, Age, Nationality, International status, Displacement status, and Educational special needs are considered sensitive attributes. Including these features in the training data may cause the model to learn biased associations (e.g., assuming that older students or males are more likely to drop out), which can result in unfair or discriminatory predictions.

The recommended practice is to:

Remove sensitive attributes from the training dataset so the model does not directly rely on them.

Store them separately for fairness auditing after training. This allows us to evaluate whether the model’s predictions are biased across sensitive groups (e.g., does the model predict higher dropout risk for women compared to men, even when other factors are the same?).
"""

sensitive_features = ["Gender", "Age at enrollment", "Nacionality",
                      "International", "Displaced", "Educational special needs"]

# Save sensitive attributes for fairness auditing
sensitive_attributes = df[sensitive_features]

# Define training features (drop Target + sensitive attributes)
X = df.drop(columns=["Target"] + sensitive_features)

# Define target variable
y = df["Target"]

# Convert categoricals into dummy/one-hot columns
X_encoded = pd.get_dummies(X, drop_first=True)  # drop_first avoids dummy variable trap

# Train / Validation / Test split
X_train, X_temp, y_train, y_temp = train_test_split(
    X_encoded, y, test_size=0.3, stratify=y, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

# Define model

xgb_model = xgb.XGBClassifier(
    objective="multi:softmax",
    num_class=len(y.unique()),  # auto-detect number of classes
    eval_metric="mlogloss",
    random_state=42,
    use_label_encoder=False
)

# Train with class balancing

sample_weights = compute_sample_weight(class_weight="balanced", y=y_train)

xgb_model.fit(
    X_train, y_train,
    sample_weight=sample_weights,
    eval_set=[(X_val, y_val)],
    verbose=True
)


# Predict & Evaluate

y_pred = xgb_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

"""We connect SHAP to the trained XGBoost model and generate SHAP values for the test set. These values show how each feature contributes to predictions."""

# Create SHAP explainer for XGBoost
explainer = shap.TreeExplainer(xgb_model)

# Explain predictions on the test set
shap_values = explainer.shap_values(X_test)

"""We visualize overall feature importance. This tells us which features are most influential across the whole dataset, helping us see general patterns."""

shap.summary_plot(shap_values, X_test, plot_type="bar")

"""Result: “SHAP shows that tuition fees up to date, scholarship quota, admission grade, previous qualification, and course choice are the most influential factors in predicting student dropout/continuation.”

👉 Interpretation (Responsible AI lens):

These results suggest that financial and academic factors are the main drivers of the model’s decisions.

This is not surprising — students struggling financially or with weaker academic history are more at risk of dropout.

Importantly, these features are not inherently sensitive attributes, but they may reflect structural inequalities (e.g., lower-income backgrounds).

Before finalizing recommendations, we will extend this analysis with LIME for local explanations and a fairness audit to ensure that these risk factors are not disproportionately impacting vulnerable subgroups

While SHAP gave us global explanations (what features matter overall), LIME lets us zoom in on individual predictions (why the model predicted dropout for this specific student).
"""

# Initialize LIME explainer
lime_explainer = LimeTabularExplainer(
    training_data=np.array(X_train),
    feature_names=X_train.columns,
    class_names=['Graduate', 'Dropout', 'Enrolled'],
    mode='classification'
)

# Pick one student from test set (example: index 15)
student_idx = 15
exp = lime_explainer.explain_instance(
    data_row=X_test.iloc[student_idx],
    predict_fn=xgb_model.predict_proba
)

# Show explanation
exp.show_in_notebook(show_table=True)
# Or save to HTML if working outside notebook
exp.save_to_file('lime_explanation.html')

"""For this student, the model predicted a 45% chance of dropout, mainly influenced by their application mode and parental occupation/qualification categories. This suggests the model has learned patterns where certain application modes or socioeconomic factors correlate with dropout risk.


While this improves interpretability, we need to pause: socioeconomic features like parental occupation or prior qualifications may reflect structural disadvantages. Even if we excluded sensitive attributes like gender or nationality, this shows proxy bias might remain, the model could indirectly penalize students from specific backgrounds. Hence, the next step is to conduct a fairness audit, so we can check whether these patterns lead to unfair outcomes
"""

sensitive_attributes = df[sensitive_features]

# Step 1: Copy sensitive attributes for test set only
sens_test = sensitive_attributes.loc[X_test.index].copy()

# Group Age into bins
sens_test["AgeGroup"] = pd.cut(sens_test["Age at enrollment"],
                               bins=[17, 22, 30, 100],
                               labels=["18-22", "23-30", "31+"])

# Simplify Nationality → Domestic vs International
sens_test["IsInternational"] = np.where(sens_test["Nacionality"] == 1,
                                        "Domestic", "International")

audit_features = ["Gender", "AgeGroup", "IsInternational", "Displaced", "Educational special needs"]

# Step 2: Run fairness audit
results = []

for feature in audit_features:
    group_values = sens_test[feature]

    mf = MetricFrame(metrics={
                        "Accuracy": accuracy_score,
                        "Selection Rate": lambda y_true, y_pred: selection_rate(y_true, y_pred, pos_label=1),
                        "Recall": lambda y_true, y_pred: recall_score(y_true, y_pred, average="macro")
                    },
                    y_true=y_test,
                    y_pred=y_pred,
                    sensitive_features=group_values)

    # Collect results by group
    df_group = mf.by_group.reset_index()
    df_group = df_group.rename(columns={feature: "Group"})
    df_group["Sensitive Feature"] = feature
    results.append(df_group)

# Combine into one table
fairness_df = pd.concat(results, ignore_index=True)

# --- Step 3: Add disparity (max - min) for each feature ---
gap_summary  = fairness_df.groupby("Sensitive Feature")[["Accuracy","Selection Rate","Recall"]].agg(['min','max'])
gap_summary["Accuracy Gap"] = gap_summary["Accuracy"]["max"] - gap_summary["Accuracy"]["min"]
gap_summary["Selection Gap"] = gap_summary["Selection Rate"]["max"] - gap_summary["Selection Rate"]["min"]
gap_summary["Recall Gap"] = gap_summary["Recall"]["max"] - gap_summary["Recall"]["min"]

# --- Step 4: Display ---
print("🔹 Fairness Audit Dashboard\n")
print(fairness_df[["Sensitive Feature","Group","Accuracy","Selection Rate","Recall"]])
print("\n🔹 Gap Summary (max-min disparity)\n")
print(gap_summary[["Accuracy Gap","Selection Gap","Recall Gap"]])

plt.figure(figsize=(8,5))
sns.heatmap(gap_summary, annot=True, cmap="Reds", cbar_kws={'label': 'Gap Value'})
plt.title("Fairness Gap Heatmap (Accuracy, Selection, Recall)")
plt.show()

"""The fairness audit reveals disparities across sensitive groups in dropout prediction. Age groups show the largest disparity, with older students much more likely to be flagged as dropouts than younger ones. Gender shows bias against females (lower accuracy and higher dropout prediction). International students have higher accuracy and recall, but are predicted as dropouts more frequently than domestic students. Displaced and special needs students display smaller but still notable differences. Overall, the results highlight the need for caution: while the model is functional, it risks unfairly treating certain student subgroups if deployed without bias mitigation."""

# Convert target to binary: dropout (1) vs non-dropout (0)
binary_y_test = (y_test == 1).astype(int)
binary_y_pred = (y_pred == 1).astype(int)

# Store results
results = []

for feat in sensitive_features:   # loop over Gender, Age, etc.
    group_values = sens_test[feat]

    # MetricFrame for per-group metrics
    mf = MetricFrame(metrics={
            "Accuracy": accuracy_score,
            "Selection Rate": selection_rate
        },
        y_true=y_test,
        y_pred=y_pred,
        sensitive_features=group_values
    )

    # Fairness metrics
    dp_diff = demographic_parity_difference(
        binary_y_test, binary_y_pred, sensitive_features=group_values
    )
    eo_diff = equalized_odds_difference(
        binary_y_test, binary_y_pred, sensitive_features=group_values
    )

    # Save
    results.append({
        "Sensitive Feature": feat,
        "Accuracy by Group": mf.by_group.to_dict(),
        "Selection Rate by Group": mf.by_group["Selection Rate"].to_dict(),
        "DP Difference": dp_diff,
        "EO Difference": eo_diff
    })

# Put everything in a dataframe for readability
fairness_results = pd.DataFrame(results)

print("\n🔹 Fairness Audit Results")
print(fairness_results[["Sensitive Feature", "DP Difference", "EO Difference"]])



